ID = "7815d88ec8f4f8e3b728f70d46494381adc86d72723fb86c5ea72940d9051f8b"
ID_human = "lactose-winter-aspen"
toml_fname = "concave_1km_naive.toml"

[coastline]
coast_file = "templating/coastlines/concave_1km.png"
start_xy = [ 0, 0,]
dx = 1000
dy = 1000
ID = "5bcd8c8119df7d6724b749453db49bb1154d7ef3c1d49cfe528f7d14f080dc98"
ID_human = "nitrogen-chicken-twelve"

[hydro_model]
duration_days = 4
ID = "afe7f70143d524fa5e6c630ef27afb383277a511df8edd9f0c560885dd4c7860"
ID_human = "oregon-uncle-burger"

[particle_model]
duration_days = 30
n_particles = 5000
dt_mins = 5
K_h = 1
particle_seed = 16
spawning_band = 60000
ID = "7815d88ec8f4f8e3b728f70d46494381adc86d72723fb86c5ea72940d9051f8b"
ID_human = "lactose-winter-aspen"

[codes]
coast_code = "Y"
resolution_code = "1"
beach_code = "A"
total = "Y1A"

[particle_model.beaching]
beaching_key = "naive"

[particle_model.beaching.fieldset_options]
