ID = "05500d24fdbb689f2aef499489f88015c638c5c8404e9e96444adecc5d089330"
ID_human = "failed-mississippi-twelve"
toml_fname = "flat_1km_oninkbr.toml"

[coastline]
coast_file = "templating/coastlines/base_1km.png"
start_xy = [ 0, 0,]
dx = 1000
dy = 1000
ID = "857c025a367b0c646bfc25671d98d48f3f2357711dfe67bc1415ade38e5aefec"
ID_human = "early-hydrogen-fifteen"

[hydro_model]
duration_days = 4
ID = "8d528b62b054e7b33f971138836a7459b69ba7b35f1a21a561562dc8c4f35cc0"
ID_human = "enemy-magnesium-yellow"

[particle_model]
duration_days = 30
n_particles = 5000
dt_mins = 5
K_h = 1
particle_seed = 16
spawning_band = 60000
ID = "05500d24fdbb689f2aef499489f88015c638c5c8404e9e96444adecc5d089330"
ID_human = "failed-mississippi-twelve"

[codes]
coast_code = "X"
resolution_code = "1"
beach_code = "E"
total = "X1E"

[particle_model.beaching]
beaching_key = "Onink2021-beach-resus"

[particle_model.beaching.fieldset_options]
beaching_timescale_days = 5
resuspension_timescale_days = 10
