name: Python testing
on: [push]
jobs:
  Running-pytests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Miniconda with dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: parcels_hons_l
          environment-file: environment.yml

          show-channel-urls: true

          use-only-tar-bz2: true
          auto-activate-base: false
          auto-update-conda: true
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          python -m pytest
